# TCL File Generated by Component Editor 9.1sp2
# Tue May 29 16:33:58 BRT 2018
# DO NOT MODIFY


# +-----------------------------------
# | 
# | compon "compon" v1.0
# | null 2018.05.29.16:33:58
# | 
# | 
# | F:/CDII/TRABALHO 1/ULA 1 BIT/compon.vhd
# | 
# |    ./compon.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module compon
# | 
set_module_property NAME compon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME compon
set_module_property TOP_LEVEL_HDL_FILE compon.vhd
set_module_property TOP_LEVEL_HDL_MODULE compon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file compon.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------
